name: flutter_playground
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # cupertino_icons: ^1.0.1
  file_picker: ^2.1.5+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.12.1
  freezed_annotation: ^0.12.0
  json_serializable: ^3.5.1
  path: ^1.7.0
  path_provider: ^1.6.27

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  integration_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
